# LOGIN #

POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyCIn_nqu-vB-rXLH0RCj4EaH5boCl4N-OU HTTP/1.1
Content-Type: application/json

{
    "email": "warmus.klaudia@gmail.com",
    "password": "test123",
    "returnSecureToken": true
}

###

# GET USER DATA

POST https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=AIzaSyCIn_nqu-vB-rXLH0RCj4EaH5boCl4N-OU HTTP/1.1
Content-Type: application/json

{
    "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2NzNkM2M5NDdhZWIxOGI2NGU1OGUzZWRlMzI1NWZiZjU3NTI4NWIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiS2xhdWRpYSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jYWtldGltZS01NjFlMyIsImF1ZCI6ImNha2V0aW1lLTU2MWUzIiwiYXV0aF90aW1lIjoxNjUxMTU3MDAxLCJ1c2VyX2lkIjoiVmQ4UDg5NXFyT2UxUnljRFFKdXdaVEZMVlNBMyIsInN1YiI6IlZkOFA4OTVxck9lMVJ5Y0RRSnV3WlRGTFZTQTMiLCJpYXQiOjE2NTExNTcwMDEsImV4cCI6MTY1MTE2MDYwMSwiZW1haWwiOiJ3YXJtdXMua2xhdWRpYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsid2FybXVzLmtsYXVkaWFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.KWHbT0RlqbezebD58T9zNbHMrD8M_YWHT13asie3dF-mKCLnG7MwPZAf-_eqndA1JYjhyz65__syFAdruUcbCcq8E4QZXv3oB_RiY1xceehR5IChr5b-kM4JQ7hy-f43x0XTtm0ku_5HhSMNsqDdMqcppz6rKhquagcyIYNwnv1wSO_9Nh9IF9_ZBmQEeub_MM9p4XCK4TSHUppwlbDpkWZaOHYaSVSGVL11z39YS3CnPYe3W-zsnVHKRFTxlTfxf3rC0sKf4zSeP3Q3TS-a1NpmqhK74hbJ8Z0d4J93VC2-DnGY0P_uR_EVcHOsdkIQQn5HffdzikzNIxWnUVvxGw"
}

### 


# GET #
GET http://localhost:3000/recipes/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2NzNkM2M5NDdhZWIxOGI2NGU1OGUzZWRlMzI1NWZiZjU3NTI4NWIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiS2xhdWRpYSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jYWtldGltZS01NjFlMyIsImF1ZCI6ImNha2V0aW1lLTU2MWUzIiwiYXV0aF90aW1lIjoxNjUxMTU2NTI4LCJ1c2VyX2lkIjoieEhqQ1BOak1HM2Y1eXRkQmhxQzlkd0g1ZDdsMiIsInN1YiI6InhIakNQTmpNRzNmNXl0ZEJocUM5ZHdINWQ3bDIiLCJpYXQiOjE2NTExNTY1MjgsImV4cCI6MTY1MTE2MDEyOCwiZW1haWwiOiJ3YXJtdXMua2xhdWRpYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsid2FybXVzLmtsYXVkaWFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.XXckOrOCKbrHBQaxtebIgaBObQhG8JVE-mr6CY0_R_RsZC8mGenrGM9cLSvt2FERpbinXzyMM-jyQQJNRaqqFAoJ30-zBk6mJneKtdjIZslGDfiL0WwiKwna0AAXoSGnWdGTtxNL7VL60zRm6DfiYUOv05RjDoues-7IK1Ug58-PkvQIa9pL9ux5nEEtNaL4LWd4Xu9SXUj7hhLg5_OOV84XFjOsAuzSjIYu8r5nsaV8CcJ-mJkiPMfgrntWRWzPZixTycxWMnQM0Ykwe9_2o7aoDmMVVVnGL7HGYRrHgEI32I41CWP6QrqRXR30bzeQF018rp0OQOybH1RZ0tdRIA

###

GET http://localhost:3000/recipes/recipe/6267ea783a37d8c0d83c7ea3 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/categories HTTP/1.1
Content-Type: application/json
###

GET http://localhost:3000/categories/Others HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/ingredients HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/ingredients/Flour/120g
Content-Type: application/json

###

GET http://localhost:3000/instructions HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/instructions/Step%201/Put%20flour%20in%20the%20bowl
Content-Type: application/json

###

GET http://localhost:3000/recipes/all/Yd91J7UKuMZ39KpmooIWfeS6LOp2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2NzNkM2M5NDdhZWIxOGI2NGU1OGUzZWRlMzI1NWZiZjU3NTI4NWIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiS2xhdWRpYSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jYWtldGltZS01NjFlMyIsImF1ZCI6ImNha2V0aW1lLTU2MWUzIiwiYXV0aF90aW1lIjoxNjUxMTU2MzAzLCJ1c2VyX2lkIjoieEhqQ1BOak1HM2Y1eXRkQmhxQzlkd0g1ZDdsMiIsInN1YiI6InhIakNQTmpNRzNmNXl0ZEJocUM5ZHdINWQ3bDIiLCJpYXQiOjE2NTExNTYzMDMsImV4cCI6MTY1MTE1OTkwMywiZW1haWwiOiJ3YXJtdXMua2xhdWRpYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsid2FybXVzLmtsYXVkaWFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.ID9Qe7EYixVc1KCRJynOXfjQyDqrNrRK35AViLYxw7jISddhIhi6TkIpqBgzVCA2z5cvPXbPlzgqZyItXMfKeFvqyyv52z_6Vn4a474KOYrgxOufU2XrODTtVFGKA3f6zjtX8lrm1nrO0edCdU_35gldA-Y3Ld4GOfX3QqpuWqMCX6X_n-qwdKrbpbY-5XESEOvB78FUOTgevRmM-sRsuGX89VBkEsagGTtBE0ZPlgqN77kNdbyJoM8_XKoC06Ii4KCDBBoIEDUdrcW-TLcapvyLus8hmfYy24uuFQCrAqZrw5t6CC5qK0_13XtXk84jCIKQXiiU-ySIPdqdLjamGQ

###

Get http://localhost:3000/users HTTP/1.1
Content-Type: application/json

###

# POST #

POST http://localhost:3000/recipes/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2NzNkM2M5NDdhZWIxOGI2NGU1OGUzZWRlMzI1NWZiZjU3NTI4NWIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiS2xhdWRpYSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jYWtldGltZS01NjFlMyIsImF1ZCI6ImNha2V0aW1lLTU2MWUzIiwiYXV0aF90aW1lIjoxNjUxMTU2MzAzLCJ1c2VyX2lkIjoieEhqQ1BOak1HM2Y1eXRkQmhxQzlkd0g1ZDdsMiIsInN1YiI6InhIakNQTmpNRzNmNXl0ZEJocUM5ZHdINWQ3bDIiLCJpYXQiOjE2NTExNTYzMDMsImV4cCI6MTY1MTE1OTkwMywiZW1haWwiOiJ3YXJtdXMua2xhdWRpYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsid2FybXVzLmtsYXVkaWFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.ID9Qe7EYixVc1KCRJynOXfjQyDqrNrRK35AViLYxw7jISddhIhi6TkIpqBgzVCA2z5cvPXbPlzgqZyItXMfKeFvqyyv52z_6Vn4a474KOYrgxOufU2XrODTtVFGKA3f6zjtX8lrm1nrO0edCdU_35gldA-Y3Ld4GOfX3QqpuWqMCX6X_n-qwdKrbpbY-5XESEOvB78FUOTgevRmM-sRsuGX89VBkEsagGTtBE0ZPlgqN77kNdbyJoM8_XKoC06Ii4KCDBBoIEDUdrcW-TLcapvyLus8hmfYy24uuFQCrAqZrw5t6CC5qK0_13XtXk84jCIKQXiiU-ySIPdqdLjamGQ

{
    "Name": "freer",
    "Category": {
        "Name": "Cakes"
    },
    "time": 10,
    "Ingredients": [
        {
            "Name": "Something",
            "Quantity": "1 kg"
        },
        {
            "Name": "Flour",
            "Quantity": "120g"
        },
        {
            "Name": "Baking powder",
            "Quantity": "1 tsp"
        }
    ],
    "Instructions": [
        {
            "Name": "Step 1",
            "Manual": "Put flour in the bowl"
        },
        {
            "Name": "Step 2",
            "Manual": "Mix it together with something"
        }
    ]
}

###

POST http://localhost:3000/categories HTTP/1.1
Content-Type: application/json

{
    "Name": "Others",
    "Url": "https://caketime.blob.core.windows.net/categories/Others.png"
}

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "Email": "warmus.klaudia@gmail.com",
    "DisplayName": "Klaudia",
    "Password": "test123"
}


### 

# PUT #

PUT http://localhost:3000/recipes/recipe/626999bed545b843e136c3b9
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2NzNkM2M5NDdhZWIxOGI2NGU1OGUzZWRlMzI1NWZiZjU3NTI4NWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY2FrZXRpbWUtNTYxZTMiLCJhdWQiOiJjYWtldGltZS01NjFlMyIsImF1dGhfdGltZSI6MTY1MTA4Nzc3NywidXNlcl9pZCI6IllkOTFKN1VLdU1aMzlLcG1vb0lXZmVTNkxPcDIiLCJzdWIiOiJZZDkxSjdVS3VNWjM5S3Btb29JV2ZlUzZMT3AyIiwiaWF0IjoxNjUxMDg3Nzc3LCJleHAiOjE2NTEwOTEzNzcsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.hAl1SAKrp8r5bizPACnIzZVl-u0n4Yc1hcnAwfNI2siQpX7AtiYWj-kIE3sESvMjoj9t8uvRoPsV92bg1gzfpfy7OqwEfrYA7icFEgWJx37Epk21AdOwSQBlcbo1ufRwr1IAjUZf_sl6X9VYHgrJQnCubxbayKFZ3LZekNbVvKOUsLjL5nXx5u3akDDvi4BU65hj08dWQevczOs27hoQWNT_LXYujT0YuFL1IQrStDFb2awkQH0ms5_LvdSud7engY3w8GZYaf7Pz-71LHYWJLqO5fncbQx372Mf6t7Zu_f5DSzU9Jl6hwQyPsecdUx6xbOGmwV4-u_qnGzqL7rR-w

###

PUT http://localhost:3000/users/Vd8P895qrOe1RycDQJuwZTFLVSA3/recipes/favorite HTTP/1.1
Content-Type: application/json

{
    "recipeId": "626aa906f14147b78d7ec2b2"
}

###

PUT http://localhost:3000/users/Vd8P895qrOe1RycDQJuwZTFLVSA3/recipes/myrecipes/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2NzNkM2M5NDdhZWIxOGI2NGU1OGUzZWRlMzI1NWZiZjU3NTI4NWIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiS2xhdWRpYSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jYWtldGltZS01NjFlMyIsImF1ZCI6ImNha2V0aW1lLTU2MWUzIiwiYXV0aF90aW1lIjoxNjUxMTU3MDAxLCJ1c2VyX2lkIjoiVmQ4UDg5NXFyT2UxUnljRFFKdXdaVEZMVlNBMyIsInN1YiI6IlZkOFA4OTVxck9lMVJ5Y0RRSnV3WlRGTFZTQTMiLCJpYXQiOjE2NTExNTcwMDEsImV4cCI6MTY1MTE2MDYwMSwiZW1haWwiOiJ3YXJtdXMua2xhdWRpYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsid2FybXVzLmtsYXVkaWFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.KWHbT0RlqbezebD58T9zNbHMrD8M_YWHT13asie3dF-mKCLnG7MwPZAf-_eqndA1JYjhyz65__syFAdruUcbCcq8E4QZXv3oB_RiY1xceehR5IChr5b-kM4JQ7hy-f43x0XTtm0ku_5HhSMNsqDdMqcppz6rKhquagcyIYNwnv1wSO_9Nh9IF9_ZBmQEeub_MM9p4XCK4TSHUppwlbDpkWZaOHYaSVSGVL11z39YS3CnPYe3W-zsnVHKRFTxlTfxf3rC0sKf4zSeP3Q3TS-a1NpmqhK74hbJ8Z0d4J93VC2-DnGY0P_uR_EVcHOsdkIQQn5HffdzikzNIxWnUVvxGw

{
    "Name": "Something tasty",
    "Category": {
        "Name": "Cakes"
    },
     "Ingredients": [
        {
            "Name": "Something",
            "Quantity": "1 kg"
        },
        {
            "Name": "Flour",
            "Quantity": "120g"
        },
        {
            "Name": "Baking powder",
            "Quantity": "1 tsp"
        }
    ],
    "Instructions": [
        {
            "Name": "Step 1",
            "Manual": "Put flour in the bowl"
        },
        {
            "Name": "Step 2",
            "Manual": "Mix it together with something"
        }
    ]
}

###

PUT http://localhost:3000/users/xHjCPNjMG3f5ytdBhqC9dwH5d7l2/recipes/myrecipes/delete HTTP/1.1
Content-Type: application/json

{
    "recipeId": "626a958b2b5ecbfb16af4457"
}



###

# DELETE #

DELETE http://localhost:3000/recipes/62640c83267b644aa617256 HTTP/1.1
Content-Type: application/json

###
